#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2009, 2010, 2011, 2012, 2013, 2014, 2017 Laboratoire de
# Recherche et Développement de l'EPITA (LRDE)
#
# This file is part of Spot, a model checking library.
#
# Spot is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Spot is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

gen=../../bin/genltl
LTL2TGBA=../../bin/ltl2tgba

echo "# Benching ltl2tgba_fm..."
echo "# the following values are also saved to file 'results.fm'"
echo "# n, states, edge, time"
for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
  $LTL2TGBA --any --low "`"$gen" --rv-counter-linear $n`" --stats="$n,%s,%e,%r"
done | tee results.fm

# echo "# Benching ltl2taa..."
# echo "# the following values are also saved to file 'results.taa'"
# echo "# n, states, transitions, time"
# for n in 1 2 3 4 5 6 7; do
#   $LTL2TGBA --any --low "`"$gen" --rv-counter-linear $n`" --stats="$n,%s,%e,%r"
# done | tee results.taa

echo "# now run 'gnuplot plot.gnu'"
