# CMake generated Testfile for 
# Source directory: /Users/jipspel/Documents/Tools/storm/src/test/storm
# Build directory: /Users/jipspel/Documents/Tools/storm/test/src/test/storm
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-test-abstraction "/Users/jipspel/Documents/Tools/storm/test/bin/test-abstraction")
set_tests_properties(run-test-abstraction PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-adapter "/Users/jipspel/Documents/Tools/storm/test/bin/test-adapter")
set_tests_properties(run-test-adapter PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-builder "/Users/jipspel/Documents/Tools/storm/test/bin/test-builder")
set_tests_properties(run-test-builder PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-logic "/Users/jipspel/Documents/Tools/storm/test/bin/test-logic")
set_tests_properties(run-test-logic PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-model "/Users/jipspel/Documents/Tools/storm/test/bin/test-model")
set_tests_properties(run-test-model PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-parser "/Users/jipspel/Documents/Tools/storm/test/bin/test-parser")
set_tests_properties(run-test-parser PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-permissiveschedulers "/Users/jipspel/Documents/Tools/storm/test/bin/test-permissiveschedulers")
set_tests_properties(run-test-permissiveschedulers PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-solver "/Users/jipspel/Documents/Tools/storm/test/bin/test-solver")
set_tests_properties(run-test-solver PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-storage "/Users/jipspel/Documents/Tools/storm/test/bin/test-storage")
set_tests_properties(run-test-storage PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-transformer "/Users/jipspel/Documents/Tools/storm/test/bin/test-transformer")
set_tests_properties(run-test-transformer PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-utility "/Users/jipspel/Documents/Tools/storm/test/bin/test-utility")
set_tests_properties(run-test-utility PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;30;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-abstraction "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-abstraction")
set_tests_properties(run-test-modelchecker-abstraction PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;37;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-csl "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-csl")
set_tests_properties(run-test-modelchecker-csl PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;37;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-exploration "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-exploration")
set_tests_properties(run-test-modelchecker-exploration PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;37;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-multiobjective "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-multiobjective")
set_tests_properties(run-test-modelchecker-multiobjective PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;37;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-reachability "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-reachability")
set_tests_properties(run-test-modelchecker-reachability PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;37;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-prctl-dtmc "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-prctl-dtmc")
set_tests_properties(run-test-modelchecker-prctl-dtmc PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;44;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
add_test(run-test-modelchecker-prctl-mdp "/Users/jipspel/Documents/Tools/storm/test/bin/test-modelchecker-prctl-mdp")
set_tests_properties(run-test-modelchecker-prctl-mdp PROPERTIES  _BACKTRACE_TRIPLES "/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;23;add_test;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;44;configure_testsuite_target;/Users/jipspel/Documents/Tools/storm/src/test/storm/CMakeLists.txt;0;")
